### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by LeeYaNam** [CPJKU/beat_this#4]
Hi, could you please tell me how to get the audio file of the Beatles dataset? I didn't find it in the article you cited in your paper. Thank you!!

**Comment by fosfrancesco** [comment]
Hello! We can't unfortunately share the audio data due to copyright reasons.
However, we will release the 50FPS mel spectrograms that we used for training, at the beginning of the next week.
I hope they will still be useful for you.

**Comment by fosfrancesco** [comment]
Spectrogram datasets are available!

**Comment by LeeYaNam** [comment]
ok! Thank you!!
